// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TransportApi.Data;

#nullable disable

namespace Reciclare.Migrations
{
    [DbContext(typeof(ReciclareContext))]
    [Migration("20220503172513_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Reciclare.Data.MaterialDTO", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                b.Property<string>("Name")
                    .HasColumnType("nvarchar(max)");

                b.HasKey("Id");

                b.ToTable("Materials");
            });

            modelBuilder.Entity("Reciclare.Data.ProdusDTO", b =>
            {
                b.Property<string>("Name")
                    .HasColumnType("nvarchar(max)");

                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                b.Property<int>("Cantitate")
                        .HasColumnType("int");

                b.Property<bool>("Produs_pubele")
                        .HasColumnType("bool");

                b.HasKey("Id");

                b.ToTable("Produs");
            });

            modelBuilder.Entity("Reciclare.Data.ContainerDTO", b =>
            {
                b.Property<string>("Name")
                    .HasColumnType("nvarchar(max)");

                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                b.HasKey("Id");

                b.ToTable("Containers");
            });
#pragma warning restore 612, 618
        }
    }
}